FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
FROM tomcat:latest-jre8
COPY C:\Users\Praveen Chandanala\git\repository\JobPortal\JobPortal.war C:\Program Files\apache-tomcat-8.0.53\webapps